import type { MockProfile, WorkType } from "./types";

export const MATCH_WORK_TYPE_OPTIONS: Array<{ value: WorkType; label: string; description: string }> = [
  { value: "content", label: "内容型", description: "偏写作、策划、研究与信息整理" },
  { value: "automation", label: "自动化型", description: "偏工作流、系统搭建、效率放大" },
  { value: "expression", label: "表达型", description: "偏视觉、视频、品牌与表达呈现" },
];

export const ALL_MATCH_TOOL_TAGS = [
  "ChatGPT",
  "Claude",
  "Perplexity",
  "Notion AI",
  "Figma",
  "Midjourney",
  "Runway",
  "CapCut",
  "Cursor",
  "Windsurf",
  "n8n",
  "Zapier",
  "Make",
  "Airtable",
  "Dify",
  "Obsidian",
  "Framer",
  "ElevenLabs",
] as const;

export const ALL_MATCH_VIBE_TAGS = [
  "结果导向",
  "爱做系统",
  "研究型",
  "视觉优先",
  "温和协作",
  "节奏稳定",
  "深夜冲刺",
  "喜欢复盘",
  "高密度输出",
  "先搭框架",
  "行动派",
  "偏实验",
] as const;

function createProfile(input: Omit<MockProfile, "avatar" | "sharedTools" | "isBot">): MockProfile {
  return {
    ...input,
    avatar: undefined,
    sharedTools: [],
    isBot: true,
  };
}

export const mockProfiles: MockProfile[] = [
  createProfile({
    id: "nova-copy-lab",
    name: "Nova",
    avatarStyle: "sunset",
    personaTitle: "长文策略写手",
    oneLiner: "把研究资料压成一页可执行提纲，是我每天最上头的事。",
    workType: "content",
    toolTags: ["ChatGPT", "Claude", "Perplexity", "Notion AI"],
    vibeTags: ["研究型", "先搭框架", "节奏稳定"],
    introPrompt: "你平时会先搭框架再开写，还是先把素材全摊出来？我最近在试把 Perplexity 和 Claude 串成固定研究流程。",
    matchScore: 92,
  }),
  createProfile({
    id: "jin-n8n-flow",
    name: "Jin",
    avatarStyle: "ocean",
    personaTitle: "自动化排班狂魔",
    oneLiner: "看到重复操作就手痒，恨不得立刻给它接个 webhook。",
    workType: "automation",
    toolTags: ["n8n", "Airtable", "ChatGPT", "Make"],
    vibeTags: ["爱做系统", "行动派", "喜欢复盘"],
    introPrompt: "你现在最想自动化掉哪一步？我最近把 Airtable 和 n8n 接成了一个内容排程台。",
    matchScore: 95,
  }),
  createProfile({
    id: "mio-visual-sprint",
    name: "Mio",
    avatarStyle: "berry",
    personaTitle: "封面图快反选手",
    oneLiner: "给我一句文案和两张参考图，我能半小时出一版情绪封面。",
    workType: "expression",
    toolTags: ["Figma", "Midjourney", "Runway", "CapCut"],
    vibeTags: ["视觉优先", "高密度输出", "偏实验"],
    introPrompt: "你会先定视觉关键词还是先找版式？我最近在试让 Midjourney 直接服务短视频封面。",
    matchScore: 89,
  }),
  createProfile({
    id: "yan-ops-notes",
    name: "Yan",
    avatarStyle: "forest",
    personaTitle: "知识库整理员",
    oneLiner: "我的快乐来自把凌乱聊天记录收束成可以复用的 SOP。",
    workType: "automation",
    toolTags: ["Obsidian", "Claude", "Dify", "Zapier"],
    vibeTags: ["爱做系统", "温和协作", "喜欢复盘"],
    introPrompt: "你会把聊天内容沉淀成模板吗？我最近在试用 Dify 做知识库入口，再用 Zapier 触发整理。",
    matchScore: 84,
  }),
  createProfile({
    id: "lark-storyboard",
    name: "Lark",
    avatarStyle: "amber",
    personaTitle: "短视频脚本编排师",
    oneLiner: "我更关心前三秒能不能把人留下来，镜头语言只是后面的事。",
    workType: "content",
    toolTags: ["ChatGPT", "CapCut", "Runway", "Perplexity"],
    vibeTags: ["高密度输出", "结果导向", "行动派"],
    introPrompt: "你做视频时最先卡住的是钩子、结构还是镜头？我最近在把脚本和镜头表拆开做。",
    matchScore: 87,
  }),
  createProfile({
    id: "iris-brand-kit",
    name: "Iris",
    avatarStyle: "iris",
    personaTitle: "品牌情绪板制造机",
    oneLiner: "视觉统一感一旦对上，整个项目推进都会顺很多。",
    workType: "expression",
    toolTags: ["Figma", "Framer", "Midjourney", "ChatGPT"],
    vibeTags: ["视觉优先", "温和协作", "先搭框架"],
    introPrompt: "你会先做 moodboard 还是先搭页面骨架？我最近在把 Framer 和 Figma 的视觉节奏统一起来。",
    matchScore: 90,
  }),
  createProfile({
    id: "roan-research-loop",
    name: "Roan",
    avatarStyle: "graphite",
    personaTitle: "选题验证控",
    oneLiner: "不先把问题定义清楚，我会很难放心开工。",
    workType: "content",
    toolTags: ["Perplexity", "Claude", "Notion AI", "Obsidian"],
    vibeTags: ["研究型", "喜欢复盘", "节奏稳定"],
    introPrompt: "你做选题时会先证伪还是先扩散？我最近在用 Perplexity 做初筛、Claude 做反方论证。",
    matchScore: 91,
  }),
  createProfile({
    id: "kei-bot-crafter",
    name: "Kei",
    avatarStyle: "mint",
    personaTitle: "Bot 工作流搭建者",
    oneLiner: "每当一个机器人能替我盯住流程，我就觉得团队又多了一个人。",
    workType: "automation",
    toolTags: ["Dify", "n8n", "Claude", "Airtable"],
    vibeTags: ["爱做系统", "结果导向", "偏实验"],
    introPrompt: "你更喜欢让机器人主动推结果，还是自己开口召唤？我最近在试多 Bot 协作的值班流。",
    matchScore: 93,
  }),
  createProfile({
    id: "pico-podcast-kit",
    name: "Pico",
    avatarStyle: "coral",
    personaTitle: "播客切片工坊",
    oneLiner: "长内容一定要切成可传播的小块，不然很多好观点会被埋掉。",
    workType: "expression",
    toolTags: ["ElevenLabs", "CapCut", "ChatGPT", "Notion AI"],
    vibeTags: ["结果导向", "温和协作", "高密度输出"],
    introPrompt: "你做内容分发时更看重密度还是节奏？我最近在试把播客切片流程完全模板化。",
    matchScore: 82,
  }),
  createProfile({
    id: "sena-prompt-garden",
    name: "Sena",
    avatarStyle: "rose",
    personaTitle: "提示词园丁",
    oneLiner: "我喜欢把有效提示词养成一套能交接的语气系统。",
    workType: "content",
    toolTags: ["ChatGPT", "Claude", "Notion AI", "Figma"],
    vibeTags: ["温和协作", "先搭框架", "喜欢复盘"],
    introPrompt: "你会把 prompt 当成写作素材还是流程零件？我最近在整理一套团队共用的语气模板。",
    matchScore: 85,
  }),
  createProfile({
    id: "taro-prototype-night",
    name: "Taro",
    avatarStyle: "cobalt",
    personaTitle: "原型夜行动物",
    oneLiner: "比起开会，我更信先拉一版原型让大家一起看着改。",
    workType: "expression",
    toolTags: ["Figma", "Framer", "ChatGPT", "Cursor"],
    vibeTags: ["行动派", "视觉优先", "深夜冲刺"],
    introPrompt: "你是先把结构跑通再补细节，还是反过来？我最近在试让 Cursor 帮我补原型里的文案骨架。",
    matchScore: 88,
  }),
  createProfile({
    id: "mara-crm-loop",
    name: "Mara",
    avatarStyle: "peach",
    personaTitle: "线索分发调度员",
    oneLiner: "销售跟进如果不自动化，团队每天都会在同样的地方漏水。",
    workType: "automation",
    toolTags: ["Airtable", "Zapier", "ChatGPT", "Make"],
    vibeTags: ["结果导向", "爱做系统", "节奏稳定"],
    introPrompt: "你做线索管理时最想先自动化哪一步？我最近把表单、标签和提醒串成一个单向漏斗。",
    matchScore: 86,
  }),
  createProfile({
    id: "echo-script-studio",
    name: "Echo",
    avatarStyle: "violet",
    personaTitle: "脚本风格校准师",
    oneLiner: "我最在意一句话说出口时的速度、力度和转折点。",
    workType: "content",
    toolTags: ["Claude", "ChatGPT", "ElevenLabs", "Perplexity"],
    vibeTags: ["研究型", "温和协作", "视觉优先"],
    introPrompt: "你写脚本时会先模拟口播吗？我最近在用 ElevenLabs 先听一遍再回修结构。",
    matchScore: 83,
  }),
  createProfile({
    id: "sol-runway-lab",
    name: "Sol",
    avatarStyle: "lime",
    personaTitle: "AI 镜头实验员",
    oneLiner: "我喜欢把不确定性当材料，很多灵感都是在试镜头的时候冒出来的。",
    workType: "expression",
    toolTags: ["Runway", "Midjourney", "CapCut", "Figma"],
    vibeTags: ["偏实验", "深夜冲刺", "视觉优先"],
    introPrompt: "你会先追求故事完整，还是先追画面冲击？我最近在试把 Runway 的镜头语言做成风格包。",
    matchScore: 91,
  }),
  createProfile({
    id: "aoki-dashboard",
    name: "Aoki",
    avatarStyle: "teal",
    personaTitle: "数据看板拼装工",
    oneLiner: "只要指标能在一个面板里说清楚，团队争论通常会少一半。",
    workType: "automation",
    toolTags: ["Airtable", "Notion AI", "Make", "Perplexity"],
    vibeTags: ["先搭框架", "结果导向", "温和协作"],
    introPrompt: "你做内部看板时最怕什么信息被忽略？我最近在试把数据说明和行动建议绑在一起。",
    matchScore: 80,
  }),
  createProfile({
    id: "nori-carousel-kit",
    name: "Nori",
    avatarStyle: "strawberry",
    personaTitle: "社媒轮播整理师",
    oneLiner: "我不喜欢只有一句观点的帖子，最好每一页都能把人往下带一步。",
    workType: "content",
    toolTags: ["ChatGPT", "Figma", "Notion AI", "Framer"],
    vibeTags: ["视觉优先", "结果导向", "高密度输出"],
    introPrompt: "你做轮播内容时会先定信息层级还是先找视觉母版？我最近在把内容结构模板化。",
    matchScore: 84,
  }),
  createProfile({
    id: "orby-support-flow",
    name: "Orby",
    avatarStyle: "sky",
    personaTitle: "客服机器人编舞师",
    oneLiner: "让机器人接住重复问题，人才有力气处理真正复杂的情况。",
    workType: "automation",
    toolTags: ["Dify", "Zapier", "ChatGPT", "Notion AI"],
    vibeTags: ["爱做系统", "温和协作", "行动派"],
    introPrompt: "你更在意机器人回答得快，还是回答得稳？我最近在做 FAQ 和人工接管的边界设计。",
    matchScore: 88,
  }),
  createProfile({
    id: "faye-portfolio-loop",
    name: "Faye",
    avatarStyle: "aurora",
    personaTitle: "作品集叙事师",
    oneLiner: "作品不是堆在一起就够了，重要的是让别人一眼看出你的判断力。",
    workType: "expression",
    toolTags: ["Figma", "Framer", "Claude", "Midjourney"],
    vibeTags: ["先搭框架", "视觉优先", "温和协作"],
    introPrompt: "你整理作品集时最难割舍的是哪部分？我最近在试把案例写法和视觉节奏一起改。",
    matchScore: 86,
  }),
  createProfile({
    id: "kio-memo-stack",
    name: "Kio",
    avatarStyle: "sand",
    personaTitle: "碎片笔记收束者",
    oneLiner: "灵感不缺，缺的是能把它们重新调出来并用上的索引。",
    workType: "content",
    toolTags: ["Obsidian", "Perplexity", "Claude", "ChatGPT"],
    vibeTags: ["研究型", "喜欢复盘", "先搭框架"],
    introPrompt: "你会回收旧笔记再写新东西吗？我最近在试让 Obsidian 自动提示可复用素材。",
    matchScore: 90,
  }),
  createProfile({
    id: "rhea-launch-board",
    name: "Rhea",
    avatarStyle: "apricot",
    personaTitle: "发布节奏指挥官",
    oneLiner: "项目到上线前那几天，最怕每个人都以为别人会补最后一刀。",
    workType: "automation",
    toolTags: ["Notion AI", "Airtable", "Zapier", "ChatGPT"],
    vibeTags: ["结果导向", "节奏稳定", "温和协作"],
    introPrompt: "你上线前会先保节奏还是保完美？我最近在做一个发布 checklist 和提醒联动板。",
    matchScore: 81,
  }),
  createProfile({
    id: "vee-live-visual",
    name: "Vee",
    avatarStyle: "ruby",
    personaTitle: "直播视觉场控",
    oneLiner: "画面节奏一乱，观众情绪就会跟着掉下来。",
    workType: "expression",
    toolTags: ["Figma", "CapCut", "Runway", "ElevenLabs"],
    vibeTags: ["视觉优先", "行动派", "深夜冲刺"],
    introPrompt: "你做直播包装时最先盯哪一块？我最近在试把预热、正片和复盘都做成统一视觉线。",
    matchScore: 87,
  }),
  createProfile({
    id: "hana-seo-loop",
    name: "Hana",
    avatarStyle: "sage",
    personaTitle: "SEO 内容工地包工头",
    oneLiner: "内容不是写完就结束，后面的更新、扩写和修补才是长期价值。",
    workType: "content",
    toolTags: ["Perplexity", "Claude", "ChatGPT", "Notion AI"],
    vibeTags: ["研究型", "结果导向", "喜欢复盘"],
    introPrompt: "你做内容更新时更看数据还是看用户意图？我最近在把旧内容更新流程拆成标准动作。",
    matchScore: 94,
  }),
  createProfile({
    id: "gale-agent-stack",
    name: "Gale",
    avatarStyle: "navy",
    personaTitle: "多代理协作试验员",
    oneLiner: "一个 agent 做不完的事，拆成小角色协作后常常突然就顺了。",
    workType: "automation",
    toolTags: ["Dify", "Claude", "Cursor", "n8n"],
    vibeTags: ["偏实验", "爱做系统", "研究型"],
    introPrompt: "你会把复杂任务拆成多个 agent 吗？我最近在试把研究、整理、输出分成三段协作。",
    matchScore: 92,
  }),
  createProfile({
    id: "uma-brand-voice",
    name: "Uma",
    avatarStyle: "gold",
    personaTitle: "品牌语气守门员",
    oneLiner: "风格统一不只是好看，它会让用户更快知道你是谁。",
    workType: "content",
    toolTags: ["Claude", "ChatGPT", "Figma", "Framer"],
    vibeTags: ["温和协作", "先搭框架", "视觉优先"],
    introPrompt: "你会先写品牌语气说明，还是先让内容跑起来再回头收口？我最近在搭一个品牌语气手册。",
    matchScore: 85,
  }),
  createProfile({
    id: "zeph-motion-pack",
    name: "Zeph",
    avatarStyle: "electric",
    personaTitle: "动效包组装师",
    oneLiner: "一个界面想让人记住，往往不是更复杂，而是节奏更准确。",
    workType: "expression",
    toolTags: ["Figma", "Runway", "Framer", "Midjourney"],
    vibeTags: ["偏实验", "视觉优先", "高密度输出"],
    introPrompt: "你做页面时会先决定节奏还是先决定风格？我最近在试把动效语言做成可复用的组件包。",
    matchScore: 93,
  }),
];
